- hosts: localhost
  environment: "{{ environment_vars }}"
  tasks:

    - name: Create Directories
      file:
        path: "{{ item }}"
        state: directory
      loop: "{{ directories }}"
      tags:
        - directories

    - name: Get Distribution Release
      shell: cat /etc/upstream-release/lsb-release | grep DISTRIB_CODENAME | awk -F= '{ print $2 }'
      register: distribution_release

    - name: Add Repository Keys
      apt_key:
        url: "{{ item }}"
        state: present
      become: yes
      loop: "{{ repository_keys }}"
      tags:
        - repos

    - name: Add Repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      become: yes
      loop: "{{ repositories }}"
      tags:
        - repos

    - name: Update package cache
      apt:
        update_cache: yes
      become: yes
      tags:
        - repos

    - name: Install Packages
      apt:
        name: "{{ packages }}"
        state: latest
      become: yes
      tags:
        - packages

    - name: Install Snaps
      snap:
        name: "{{ snap_packages }}"
        state: present
        classic: yes
      become: yes
      tags:
        - snap

    - name: Update Pip
      pip:
        name: pip
        state: latest
      become: yes
      tags:
        - python

    - name: Install Pip packages
      pip:
        name: "{{ pip_packages }}"
        state: latest
        extra_args: --user
      tags:
        - python

    - name: Activate Python Argcomplete
      command: activate-global-python-argcomplete --user
      tags:
        - python

    - import_role:
        name: roles/keys
      tags:
        - keys

    - name: Initialize Password Store
      command: pass init pass-{{ username }}
      tags:
        - pass

    - name: Install Oh-My-Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
      tags:
        - shell

    - name: Change Default Shell
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
      become: yes
      tags:
        - shell
    
    - import_role:
        name: roles/docker
      tags:
        - docker
    
    - import_role:
        name: roles/config
      tags:
        - config

    - import_role:
        name: roles/i3
      tags:
        - i3config